In [1]:
import numpy as np

##  Row and column vectors

In [4]:
c1 = np.array([1, 5, -3, 2])
c2 = np.array([8, 2, 4, 7])

c1 + c2

array([9, 7, 1, 9])

In [5]:
c1 + c2*10

array([81, 25, 37, 72])

In [6]:
c1 * c2

array([  8,  10, -12,  14])

In [40]:
c2_trans = c2.T

# c1 + c2_trans # can't add row to column vector

## Vector dot product

In [34]:
np.dot(c1, c2)

20

In [38]:
c1_trans = c1.T
np.dot(c1_trans, c2)

20

## 2-d arrays and matrices

In [94]:
m = np.array([[1, 2, 3], [-2, 3, 7]])
v = np.array([[1], [0], [-1]])

np.dot(m, v)

array([[-2],
       [-9]])

In [96]:
# np.dot(v, m) # is invalid

In [100]:
np.dot(c1, c2)

20

In [102]:
w = np.matrix([1, 5, 0])
x = np.matrix([[8], [2]])

np.multiply(w, x)

matrix([[ 8, 40,  0],
        [ 2, 10,  0]])

## Python

In [103]:
def add_two_lists(a, b):
    return [a + b for (a, b) in zip(a,b)]

In [104]:
def dot(v1, v2):
    return sum(v1 * v2 for v1, v2 in zip(v1, v2))

In [106]:
def add_n(n):
    def new_fun(v):
        return [elt + n for elt in v]
    return new_fun

The ability to create and return functions as values in Python is crucial here. add_n creates and returns the new function new_fun, which is then called later on the argument vector. The variable n is defined in the surrounding scope of new_fun (having been created when add_n is called with a particular value for n), and so the lookup of n evaluates to that value when the body of new_fun is eventually evaluated later.

In [109]:
add_n(10)([1, 5, 3])

[11, 15, 13]

In [128]:
def array_mult(A, B):
    return [[sum([x*y for x, y in zip(row, col)]) for col in zip(*B)] for row in A] 
    

M1 = [[1, 2, 3], [-2, 3, 7]]
M2 = [[1,0,0],[0,1,0],[0,0,1]]

array_mult(M1, M2)

[[1, 2, 3], [-2, 3, 7]]

In [133]:
def array_mult2(A, B):
    A_n = len(A) 
    A_m = len(A[0])
    B_n = len(B)
    B_m = len(B[0])
    assert A_m == B_n

    R_n = A_n
    R_m = B_m
    R = [[0 for j in range(R_m)] for i in range(R_n)]

    def row(M, r): return M[r]
    def col(M, c): return [v[c] for v in M]
    def dot(v1, v2): return sum([x*y for x, y in zip(v1, v2)])

    for i in range(R_n):
        for j in range(R_m):
            R[i][j] = dot(row(A,i), col(B,j))
    return R

In [134]:
M1 = [[1, 2, 3], [-2, 3, 7]]
M2 = [[1,0,0],[0,1,0],[0,0,1]]

array_mult2(M1, M2)

[[1, 2, 3], [-2, 3, 7]]